import Head from 'next/head'
import styles from '../styles/Home.module.css'

//  Imported components
import ProfileCard from '../components/profile-card'

// Components content
import profileCardContent from '../content/profile-card.content'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ProfileCard {...profileCardContent}/>
      </main>
    </div>
  )
}
